version: 2
jobs:
  test-lint:
    parallelism: 1
    working_directory: ~/repo
    docker:
      - image: manifoldai/docker-ml-dev:1.0

    steps:
      - checkout
      - run:
          name: Black lint check
          command: |
            pip install black && black --check ./src
      - run:
          name: Flake8 lint check
          command: |
            flake8 --max-line-length 120 ./src

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-lint
